### Create products
POST http://localhost:8080/products
Content-Type: application/json

{
  "product_id": "001-0005",
  "name": "Phosphate Microgranular Premium 30",
  "presentation": "30 kg",
  "description": "Light package for localized or nursery use"
}

### Add stock (IN) for product
POST http://localhost:8080/movements
Content-Type: application/json

{
  "product_id": "001-0005",
  "type": "IN",
  "quantity": 60,
  "notes": "Initial stock"
}

### If try to sell (OUT) more than available -> should return 400
POST http://localhost:8080/movements
Content-Type: application/json

{
  "product_id": "001-0005",
  "type": "OUT",
  "quantity": 90,
  "notes": "Sale exceeding stock"
}

### Get stock for product
GET http://localhost:8080/movements/stock/001-0005

### List products
GET http://localhost:8080/products

### List movements
GET http://localhost:8080/movements

### Register New User
# This creates a user account with hashed password
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "username": "inventarioAdmin",
    "email": "admin@dcp.com",
    "password": "myPassword123",
    "firstName": "Juan",
    "lastName": "Perez"
}

### Login User
# This starts a session (sets the connect.sid cookie)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "inventarioAdmin",
    "password": "myPassword123"
}

### Logout User

GET http://localhost:8080/logout